const ac = {
    REGISTER_USER_START: 'REGISTER_USER_START',
    REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
    REGISTER_USER_ERROR: 'REGISTER_USER_ERROR',
    LOG_USER_OUT: 'LOG_USER_OUT',
    LOG_USER_START: 'LOG_USER_START',
    LOG_USER_SUCCESS: 'LOG_USER_SUCCESS',
    LOG_USER_ERROR: 'LOG_USER_ERROR',
    SET_USER_ID: 'SET_USER_ID',
    REMOVE_ERROR: "REMOVE_ERROR",
    SET_USER_DATA_START: "SET_USER_DATA_START",
    SET_USER_DATA_SUCCESS: "SET_USER_DATA_SUCCESS",
    SET_USER_DATA_ERROR: "SET_USER_DATA_ERROR",
    USER_DATA_REMOVE: "USER_DATA_REMOVE",
    ALL_USERS_START: "ALL_USERS_START",
    ALL_USERS_SUCCESS: "ALL_USERS_SUCCESS",
    ALL_USERS_ERROR: "ALL_USERS_ERROR",
    ALL_USERS_REMOVE: "ALL_USERS_REMOVE",
    SET_HOLIDAY_START: "SET_HOLIDAY_START",
    SET_HOLIDAY_SUCCESS: "SET_HOLIDAY_SUCCESS",
    SET_HOLIDAY_ERROR: "SET_HOLIDAY_ERROR",
    SET_WISHES_ERROR: "SET_HOLIDAY_ERROR",
    SET_WISHES_START: "SET_HOLIDAY_ERROR",
    SET_WISHES_SUCCESS: "SET_HOLIDAY_ERROR",


}

export default ac;